INSERT INTO "public"."events" ("id", "title", "description", "start_date", "end_date", "registration_start_date", "registration_end_date", "mode", "status", "location", "max_participants", "current_participants", "registration_link", "image_url", "tags", "is_featured", "organizer_name", "organizer_email", "organizer_phone", "event_fee", "certificate_available", "agenda", "created_at", "updated_at", "slug", "registration_platform", "prerequisites", "registration_process", "selection_process", "organizer_website", "has_ppi", "benefits", "prizes") VALUES ('2994f309-56b9-47f2-b652-ed3f8cdc8fef', 'Adobe India Hackathon 2025', 'Reimagine PDFs with intelligence in the Adobe India Hackathon. Build, connect, and create a smart document experience. Participate in coding, prototyping, and pitch rounds to win MacBooks, iPads, and internships with Adobe!', '2025-07-11 06:30:00+00', '2025-09-05 08:30:00+00', '2025-06-17 06:30:00+00', '2025-07-10 18:29:00+00', 'hybrid', 'ongoing', 'Online + In-Person (Finale in Noida)', null, '120316', 'https://unstop.com/o/oDTg1KU?lb=70BMsNY&utm_medium=Share&utm_source=shortUrl', 'https://d8it4huxumps7.cloudfront.net/uploads/images/6837eb4eddf8e_adobe-india-hackathon.png?d=1920x1920', '{
"Adobe","Internship","Coding","competition","Hackathon"}', 'true', 'Adobe', 'support@unstop.com', '', '0.00', 'true', '• Round 1: Online MCQ + Coding
• Round 2: Build & Connect
• Round 3: Experience Prototype
• Round 4: Grand Finale at Noida HQ

Exciting rewards + PPIs + Internships', '2025-06-22 13:12:45.288305+00', '2025-06-24 15:36:18.878777+00', 'adobe-india-hackathon-2025', 'Unstop', '["Must be a full-time B.Tech/B.E., M.Tech/M.E. or dual degree students.", "Graduating in 2026, 2027, 2028, or 2029 from Engineering colleges in India.", "Only teams of 2-3 members allowed.", "All members must be from the same college.", "Cross-year and cross-specialisation teams allowed.", "Cross-college teams not allowed."]', '["Every team member must register using their active WhatsApp number. This is required for important announcements and communication during the hackathon.", "Students should register using their official college or university email ID. If it’s not available, they may use their personal Gmail ID instead.", "A single college or university can have multiple teams participating. There is no limit on the number of teams from the same institution.", "All members in a team must belong to the same college or university. Cross-college teams are not allowed.", "Each student can be part of only one team. Duplicate registrations or participation in multiple teams is strictly prohibited."]', '["All registered team members must participate in Round 1, which includes a 1-hour online assessment with MCQs and a coding challenge. The average score of all team members will be considered for shortlisting.", "Based on Round 1 performance, selected teams will proceed to the Build and Connect Round. Here, they will receive a detailed problem statement and must submit a working solution within the given time frame.", "Top-performing teams from Round 2 will be shortlisted for the Experience & Insight Prototype round, where they will build a functional web interface to showcase their idea.", "Finalists from the prototype round will be invited to present their solutions in the Grand Finale at Adobe headquarters. Presentations will be evaluated by Adobe''s senior leadership.", "Overall evaluation will be based on creativity, technical implementation, teamwork, problem-solving ability, and presentation quality."]', 'https://www.adobe.com/', 'true', '[{
"icon": "Code", "type": "technical_skill", "description": "Gain hands-on experience with cutting-edge technologies."}, {
"icon": "Users", "type": "networking", "description": "Network with industry leaders and potential employers."}, {
"icon": "Trophy", "type": "rewards", "description": "Win MacBook Air, iPad Air, many prizes and recognition for your innovative solutions."}, {
"icon": "Award", "type": "certification", "description": "Receive a PPI and certificate to boost your resume."}, {
"icon": "Briefcase", "type": "career_opportunity", "description": "A potential Opportunity to get pre-placement interviews (PPIs) with Adobe India."}]', '[{
"type": "Trophy", "position": "Winner", "description": "Each member of the Winning team will receive a MacBook Air"}, {
"type": "Trophy", "position": "First Runners-Up", "description": "Each member of the Winning team will receive an iPad Air"}, {
"type": "Briefcase", "position": "Top 50 participants", "description": "Top 50 participants to get PPIs and a chance to intern with Adobe with a stipend of INR 1,00,000 per month. <b>Note: Only the 2027 batch is eligible for PPIs for an Internship.</b>"}, {
"type": "Trophy", "position": "National Finalists", "description": "National Finalists to get exclusive goodie bags from Adobe and Adobe Acrobat Pro Licenses"}, {
"type": "Trophy", "position": "50 Shortlisted Teams", "description": "50 shortlisted team to get certificates from Adobe"}, {
"type": "Award", "position": "Participation Certificate", "description": "Certificate of participation for all attendees."}]');