name: Auto Assign & Label Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  assign-label-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels to issue
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            gssoc25
            level-required

      - name: Assign issue to author
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}

      - name: Post welcome comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ---
            ## 👋 Hello @${{ github.actor }}!

            🎯 Your issue has been:
            - 🏷️ **Labeled:** `gssoc25`, `level-required`
            - 🙋‍♂️ **Assigned to you**

            ---
            ### ✅ You may now start working on this issue!

            💬 **Strict Rule for Communication:**
            > 📌 _All doubts must be asked **only on [our Discord Server](https://discord.gg/zsuxfG76PS)**._

            🚫 **Avoid:**
            - Tagging mentors or project admins unnecessarily
            - Asking for label/assignment changes

            ---
            🛠️ Let's build something awesome together!

            > 🤖 *This is an auto-generated message by the TechX Ninjas bot.*
